# works as of pad version 2023-11-21
RotateIfItWasGood ← setinv∘¯⌅(⊂⊃↘↙ ⊃((◿|⋅⋅0)=0.⧻:)⋅∘)
---
⍤:≍, ↻ 3 1_2_3_4 RotateIfItWasGood 3 1_2_3_4
⍤:≍, ↻ ¯3 1_2_3_4 RotateIfItWasGood ¯3 1_2_3_4
⍤:≍, ↻ ¯6 1_2_3_4 RotateIfItWasGood ¯6 1_2_3_4
⍤:≍, ⍘↻ 3 1_2_3_4 ⍘RotateIfItWasGood 3 1_2_3_4
⍤:≍, ↻ 0 1_2_3_4 f 0 1_2_3_4
⍤:≍, ⍘↻ 0 1_2_3_4 ⍘RotateIfItWasGood 0 1_2_3_4
⍤:≍, ↻ 0 [] RotateIfItWasGood 0 []
⍤:≍, ⍘↻ 0 [] ⍘RotateIfItWasGood 0 []
---
